### ISSUE TITLE
new FEP WUs are crashing right away on FAH - proposed fix

### ISSUE THREAD

**Issue by vvoelz** [vvoelz/covid-FAH-CPU#4]
For some percentage of new p14346 WUs being internally tested, they fail right away with an error like this:

```
-------------------------------------------------------
Program gmx, VERSION 5.0.4
Source code file: /Users/suvince/local/gromacs-5.0.4/src/gromacs/mdlib/pme.c, line: 754

Fatal error:
17 particles communicated to PME rank 2 are more than 2/3 times the cut-off out of the domain decomposition cell of their charge group in dimension x.
This usually means that your system is not well equilibrated.
```

...which made me think it had to be something in the way each new `*.tpr` gets build with `FEP/scripts/continue_a_tpr.py`

One reason might be that the velocities are being re-generated each time -- OOPS!    VINCE needs to fix this and see if it works.    In the mdp file, currently 
```
; GENERATE VELOCITIES FOR STARTUP RUN
gen_vel                  = yes
```

should be `gen_vel                  = yes`   which will require new functionality for the class in `expanded.py`

**Comment by mrshirts** [comment]
I doubt the problem is new velocities being generated.  One question is if the right final lambda state is being used to initialize the new simulation- checking if there is a bug there is the likeliest thing. That's what was most likely to cause an error before.

**Comment by vvoelz** [comment]
I just pushed to master FEP/debug/PROJ14346-RUN6-CLONE4 for debugging FYI

**Comment by vvoelz** [comment]
ACK!   AW crap I have to teach, but you are right -- `init-lambda-state` is not being read and set in my scripts.    This should do it

**Comment by vvoelz** [comment]
This has been figured out -- the hypothesis was correct and has been fixed
